//! Rectangular progressive **B-VOP encoder** — §7.6.9 mode decision +
//! §6.2.6 emission over the P-VOP encoder's block machinery.
//!
//! Per macroblock the walk evaluates the four §7.6.9 prediction modes
//! against the two bracketing anchors (always the **closed-loop**
//! reconstructions — the decoder-walk outputs of the emitted anchor
//! units):
//!
//! * **direct** (§7.6.9.5) — the per-sub-block `(MVF[i], MVB[i])`
//!   pairs derived from the co-located future-anchor macroblock's
//!   block vectors via the §7.6.9.5.2 TRB/TRD scaling, searched over a
//!   small `MVD` window (the delta is coded with `f_code == 1` and
//!   predictor zero, §7.6.8);
//! * **forward** (§7.6.9.2) / **backward** (§7.6.9.3) — one 16×16 MV
//!   against the past / future anchor (the P encoder's §7.6 motion
//!   search + sub-pel refinement), coded against the §7.6.8 running
//!   per-direction predictor (reset at each row start, updated only by
//!   macroblocks coding that direction);
//! * **interpolated** (§7.6.9.4) — both vectors, averaged prediction.
//!
//! Every candidate's prediction is generated by the decoder's own
//! §7.6.9 machinery ([`BVopMbDecode::reconstruct`] with a zero
//! residual), so the mode decision scores exactly what a conformant
//! decoder will reconstruct. Emission follows the §6.2.6 B-VOP
//! macroblock syntax: `modb` (Table B.3 — `"1"` for a direct zero-delta
//! macroblock with no coded blocks, `"01"` without `cbpb`, `"00"` with),
//! `mb_type` (Table B.4), `cbpb`, `dbquant` (Table 6-33; this encoder
//! keeps a per-VOP quantiser, delta `0`), the `motion_vector()` bodies
//! in §6.2.6 order (forward, backward, direct), and the Table B.17
//! inter `block()` bodies. A macroblock whose co-located future-P
//! macroblock was skipped transmits **no bits at all** (§6.2.6 /
//! §6.3.6 `co_located_not_coded`; §7.6.9.6 reconstructs it as a
//! forward zero-MV copy).
//!
//! The emitted VOP is decoded back through the crate's own
//! [`decode_b_vop_macroblocks`] +
//! [`assemble_b_vop_frame`](crate::frame_decode::assemble_b_vop_frame)
//! walk, closing the loop.
//!
//! This encoder emits **progressive** B-VOPs only, where the
//! §7.7.2.2 interlaced-direct spec-vs-ecosystem divergence (and its
//! transmitted-`MVD == (0, 0)` sub-behaviour, `crate::compat`) cannot
//! arise — a progressive direct macroblock's derivation is identical
//! under both behaviour modes.
//!
//! Provenance: §6.2.5/§6.2.6 syntax, §6.3.6 semantics, §7.6.7–§7.6.9
//! prediction from ISO/IEC 14496-2:2004 (3rd edition), read from
//! `docs/video/mpeg4-visual/ISO_IEC_14496-2-2004-3rd-edition.txt`,
//! via the crate's decoder transcriptions. No third-party source was
//! consulted.

use crate::bitreader::BitReader;
use crate::bitwriter::BitWriter;
use crate::block::{nonintra_quant_matrix, InterMacroblock};
use crate::bvop::BVopMbType;
use crate::bvop_mv::{BVopAnchorPlanes, BVopMbDecode};
use crate::bvop_prediction::{BVopMvPair, BVopPredictionMode, BVopSampleMode, MB_SUB_BLOCKS};
use crate::framestore::{DecodedFrame, FrameStore};
use crate::ivop_encode::{EncoderConfig, FrameView};
use crate::motion::{
    direct_mode_motion_vector, DirectCoLocatedMv, DirectMvUnits, MotionVector, MotionVectorDelta,
};
use crate::pvop_encode::{estimate_motion, quantise_inter_block, sample_mode_of, source_luma_mb};
use crate::pvop_mv::PvopMbMotion;
use crate::texture::{AcEvent, TcoefTable};
use crate::vlc_encode::{put_ac_events, put_motion_vector};
use crate::vop::{parse_vop_header_body, vop_time_increment_bits, VopCodingType, VopContext};
use crate::vop_decode::decode_b_vop_macroblocks;

const VOP_START_CODE: u32 = 0x0000_01B6;

/// Direct-mode `MVD` search radius (in the VOL's MV units, each
/// component; the delta is coded with `f_code == 1`).
pub const DIRECT_SEARCH: i32 = 2;

/// SAD bias favouring direct mode over the single-MV modes (the three
/// §6.2.6 mode-header + motion bits the cheaper form saves).
pub(crate) const ONE_MV_MODE_BIAS: u32 = 64;
/// SAD bias for interpolated mode (two motion bodies).
pub(crate) const INTERP_MODE_BIAS: u32 = 96;

/// Emit a §6.2.5 B-VOP header (`vop_fcode_forward == vop_fcode_backward
/// == fcode`). The writer is left mid-unit — the macroblock walk
/// follows.
#[allow(clippy::too_many_arguments)]
pub fn write_b_vop_header(
    bw: &mut BitWriter,
    resolution: u16,
    modulo_time_base: u32,
    time_increment: u16,
    quant: u32,
    fcode: u8,
    interlace: Option<crate::ivop_encode::VopInterlaceFlags>,
    intra_dc_vlc_thr: u8,
) {
    bw.write_start_code(VOP_START_CODE);
    bw.write_bits(0b10, 2); // vop_coding_type = B
    for _ in 0..modulo_time_base {
        bw.write_bit(true);
    }
    bw.write_bit(false); // modulo_time_base terminator
    bw.write_marker();
    bw.write_bits(
        u32::from(time_increment),
        usize::from(vop_time_increment_bits(resolution)),
    );
    bw.write_marker();
    bw.write_bit(true); // vop_coded = 1 (no vop_rounding_type for B)
    assert!(intra_dc_vlc_thr <= 7, "intra_dc_vlc_thr is a 3-bit field");
    bw.write_bits(u32::from(intra_dc_vlc_thr), 3); // intra_dc_vlc_thr (no intra MBs in B)
    if let Some(flags) = interlace {
        flags.write(bw); // top_field_first + alternate_vertical_scan_flag
    }
    assert!((1..=31).contains(&quant), "vop_quant {quant} out of range");
    bw.write_bits(quant, 5);
    assert!((1..=7).contains(&fcode), "vop_fcode {fcode} out of range");
    bw.write_bits(u32::from(fcode), 3); // vop_fcode_forward
    bw.write_bits(u32::from(fcode), 3); // vop_fcode_backward
}

/// Per-VOP B encode statistics (mode-decision observability).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct BVopEncodeStats {
    /// §6.2.6 zero-bit macroblocks (co-located future-P MB skipped).
    pub zero_bit: usize,
    /// Macroblocks that carried a non-zero `dbquant`.
    pub dbquant: usize,
    /// Video packets cut inside the VOP (resync markers emitted).
    pub packets: usize,
    /// `modb == "1"` macroblocks (direct, zero delta, no residual).
    pub modb_one: usize,
    /// Explicit direct macroblocks.
    pub direct: usize,
    /// Forward-mode macroblocks.
    pub forward: usize,
    /// Backward-mode macroblocks.
    pub backward: usize,
    /// Interpolated (bidirectional) macroblocks.
    pub interpolated: usize,
}

/// Emit a Table B.4 B-VOP `mb_type` codeword.
pub(crate) fn put_b_mb_type(bw: &mut BitWriter, mb_type: BVopMbType) {
    let (code, len) = match mb_type {
        BVopMbType::Direct => (0b1, 1),
        BVopMbType::Interpolated => (0b01, 2),
        BVopMbType::Backward => (0b001, 3),
        BVopMbType::Forward => (0b0001, 4),
    };
    bw.write_bits(code, len);
}

/// §7.6.5 chroma reduction on the VOL's grid.
fn chroma_reduce(mvs: &[MotionVector], mode: BVopSampleMode) -> MotionVector {
    match mode {
        BVopSampleMode::HalfPel => {
            crate::chroma_mv::chroma_mv_from_luma_blocks(mvs).expect("1..=4 vectors always reduce")
        }
        BVopSampleMode::QuarterPel { .. } => crate::chroma_mv::chroma_mv_from_luma_blocks_qpel(mvs)
            .expect("1..=4 vectors always reduce"),
    }
}

/// One fully-resolved mode candidate: the decoder-shaped motion state
/// plus the direct delta it was built from (relevant for
/// [`BVopMbType::Direct`] only).
pub(crate) struct ModeCandidate {
    pub(crate) decode: BVopMbDecode,
    pub(crate) direct_delta: MotionVectorDelta,
}

/// Build the [`BVopMbDecode`] for a non-direct mode.
pub(crate) fn one_mv_candidate(
    mb_type: BVopMbType,
    fwd: MotionVector,
    bwd: MotionVector,
    mode: BVopSampleMode,
) -> ModeCandidate {
    let zero = MotionVector { x: 0, y: 0 };
    let (prediction_mode, fwd_chroma, bwd_chroma) = match mb_type {
        BVopMbType::Forward => (
            BVopPredictionMode::ForwardOnly,
            chroma_reduce(&[fwd], mode),
            zero,
        ),
        BVopMbType::Backward => (
            BVopPredictionMode::BackwardOnly,
            zero,
            chroma_reduce(&[bwd], mode),
        ),
        BVopMbType::Interpolated => (
            BVopPredictionMode::Bidirectional,
            chroma_reduce(&[fwd], mode),
            chroma_reduce(&[bwd], mode),
        ),
        BVopMbType::Direct => unreachable!("direct candidates are built by direct_candidate"),
    };
    ModeCandidate {
        decode: BVopMbDecode {
            mb_type,
            prediction_mode,
            cbpb: None,
            dbquant_delta: None,
            mvs: [BVopMvPair {
                forward: fwd,
                backward: bwd,
            }; MB_SUB_BLOCKS],
            forward_chroma_mv: fwd_chroma,
            backward_chroma_mv: bwd_chroma,
        },
        direct_delta: MotionVectorDelta { dx: 0, dy: 0 },
    }
}

/// Build the [`BVopMbDecode`] for a direct-mode candidate with `delta`.
pub(crate) fn direct_candidate(
    co_mvs: [DirectCoLocatedMv; MB_SUB_BLOCKS],
    delta: MotionVectorDelta,
    trb: i32,
    trd: i32,
    mode: BVopSampleMode,
) -> ModeCandidate {
    let zero = MotionVector { x: 0, y: 0 };
    let mut mvs = [BVopMvPair {
        forward: zero,
        backward: zero,
    }; MB_SUB_BLOCKS];
    for (pair, co) in mvs.iter_mut().zip(co_mvs) {
        let d = direct_mode_motion_vector(co, delta, trb, trd, DirectMvUnits::Match)
            .expect("trb/trd validated at VOP entry");
        *pair = BVopMvPair {
            forward: d.forward,
            backward: d.backward,
        };
    }
    let fwd: Vec<MotionVector> = mvs.iter().map(|p| p.forward).collect();
    let bwd: Vec<MotionVector> = mvs.iter().map(|p| p.backward).collect();
    ModeCandidate {
        decode: BVopMbDecode {
            mb_type: BVopMbType::Direct,
            prediction_mode: BVopPredictionMode::Direct,
            cbpb: None,
            dbquant_delta: None,
            mvs,
            forward_chroma_mv: chroma_reduce(&fwd, mode),
            backward_chroma_mv: chroma_reduce(&bwd, mode),
        },
        direct_delta: delta,
    }
}

/// Luma SAD of a candidate's §7.6.9 prediction against the source
/// macroblock (prediction generated by the decoder's own machinery
/// with a zero residual).
pub(crate) fn candidate_sad(
    cand: &ModeCandidate,
    anchors: &BVopAnchorPlanes<'_>,
    src: &[[i32; 16]; 16],
    mb_x: i32,
    mb_y: i32,
    mode: BVopSampleMode,
) -> u32 {
    let recon = cand
        .decode
        .reconstruct(anchors, &InterMacroblock::zero(), mb_x, mb_y, 0, mode, 8);
    let mut sad = 0u32;
    for (j, row) in src.iter().enumerate() {
        for (i, &s) in row.iter().enumerate() {
            sad += (s - recon.luma[j][i]).unsigned_abs();
        }
    }
    sad
}

/// Encode one rectangular progressive B-VOP between the two anchors in
/// `store` (the §7.6.1 forward + backward chain — both must be the
/// closed-loop reconstructions of the emitted anchor units).
///
/// * `anchor_motion` — the future (backward) anchor's per-macroblock
///   decoded motion in raster order (`None` after an intra anchor),
///   exactly what [`decode_b_vop_macroblocks`] consumes on the decode
///   side: it drives the §6.2.6 `co_located_not_coded` zero-bit gating
///   and the §7.6.9.5.2 co-located vectors.
/// * `trb` / `trd` — the §7.6.7 temporal references in VOL ticks
///   (`0 < trb < trd`).
///
/// Returns the emitted unit, the closed-loop reconstruction (the
/// crate's own decode of the freshly emitted bits), and the mode
/// statistics.
#[allow(clippy::too_many_arguments)]
pub fn encode_b_vop(
    vol: &crate::vol::VolHeader,
    cfg: &EncoderConfig,
    frame: &FrameView<'_>,
    store: &FrameStore,
    anchor_motion: Option<&[PvopMbMotion]>,
    trb: i32,
    trd: i32,
    modulo_time_base: u32,
    time_increment: u16,
    qp: u32,
) -> (Vec<u8>, DecodedFrame, BVopEncodeStats) {
    assert!((1..=31).contains(&qp), "vop_quant {qp} out of range");
    assert!(
        trd > 0 && trb > 0 && trb < trd,
        "§7.6.7 requires 0 < TRB ({trb}) < TRD ({trd})"
    );
    let (mb_width, mb_height) = cfg.mb_dimensions();
    if let Some(m) = anchor_motion {
        assert_eq!(m.len(), mb_width * mb_height, "anchor motion grid shape");
    }
    let w_inter = nonintra_quant_matrix(vol);
    let mode = sample_mode_of(vol);
    let (fwd_anchor, bwd_anchor) = store
        .b_vop_references()
        .expect("both anchors present before a B-VOP");
    let fwd_luma = fwd_anchor.luma_reference();
    let bwd_luma = bwd_anchor.luma_reference();
    let fwd_cb = fwd_anchor.cb_reference();
    let bwd_cb = bwd_anchor.cb_reference();
    let fwd_cr = fwd_anchor.cr_reference();
    let bwd_cr = bwd_anchor.cr_reference();
    let anchors = BVopAnchorPlanes {
        forward_luma: &fwd_luma,
        backward_luma: &bwd_luma,
        forward_cb: &fwd_cb,
        backward_cb: &bwd_cb,
        forward_cr: &fwd_cr,
        backward_cr: &bwd_cr,
    };

    assert!(
        !cfg.interlaced,
        "interlaced B-VOPs are coded by encode_b_vop_interlaced"
    );
    let fcode = cfg.fcode;
    let mut header = BitWriter::new();
    write_b_vop_header(
        &mut header,
        cfg.time_increment_resolution,
        modulo_time_base,
        time_increment,
        qp,
        fcode,
        None,
        cfg.intra_dc_vlc_thr,
    );
    // B-VOPs always use the combined syntax (§6.2.5.3 NOTE), video
    // packets included.
    let mut pw = crate::packet_encode::PacketWriter::new(
        header,
        cfg.resilience,
        crate::packet_encode::PacketVopInfo {
            coding_type: VopCodingType::B,
            fcode_fwd: fcode,
            fcode_bwd: fcode,
            modulo_time_base,
            time_increment,
            time_increment_bits: vop_time_increment_bits(cfg.time_increment_resolution),
            intra_dc_vlc_thr: cfg.intra_dc_vlc_thr,
            total_macroblocks: (mb_width * mb_height) as u32,
            interlaced: false,
            sprite_trajectory: None,
        },
        crate::packet_encode::Layout::Combined,
    );

    let mut stats = BVopEncodeStats::default();
    // §6.3.7 running quantiser (seeded by vop_quant, moved by dbquant
    // on the macroblocks whose syntax carries it).
    let vop_qp = qp;
    let mut running_qp = vop_qp;
    for mb_row in 0..mb_height {
        // §7.6.8: the running per-direction predictors reset at each
        // row start (mirrors BVopMvDriver::start_row).
        let mut pred_f = MotionVector { x: 0, y: 0 };
        let mut pred_b = MotionVector { x: 0, y: 0 };
        for mb_col in 0..mb_width {
            let idx = mb_row * mb_width + mb_col;
            if pw.maybe_cut(idx, running_qp) {
                // §7.6.8 / §E.1.2: a resync marker resets the running
                // predictors like a row start (BVopMvDriver::start_row)
                // and re-seeds the quantiser from quant_scale.
                pred_f = MotionVector { x: 0, y: 0 };
                pred_b = MotionVector { x: 0, y: 0 };
            }
            let co_motion = anchor_motion.map(|m| m[idx]);

            // §6.2.6 co_located_not_coded: no bits at all.
            if matches!(co_motion, Some(PvopMbMotion::Skipped)) {
                stats.zero_bit += 1;
                continue;
            }

            let co_mvs: [DirectCoLocatedMv; MB_SUB_BLOCKS] = match co_motion {
                Some(PvopMbMotion::OneMv(mv)) => [DirectCoLocatedMv::Mv(mv); MB_SUB_BLOCKS],
                Some(PvopMbMotion::FourMv(mvs)) => mvs.map(DirectCoLocatedMv::Mv),
                // Intra co-located MB / intra-only anchor: §7.6.9.5.1
                // final sentence — direct stays enabled with MV = 0.
                Some(PvopMbMotion::Intra) | None => {
                    [DirectCoLocatedMv::TransparentOrAbsent; MB_SUB_BLOCKS]
                }
                Some(PvopMbMotion::Skipped) => unreachable!("handled above"),
            };

            let (mb_x, mb_y) = ((mb_col * 16) as i32, (mb_row * 16) as i32);
            let src = source_luma_mb(frame, mb_row, mb_col);

            // ---- Candidate modes -------------------------------------
            // Direct: search the MVD window.
            let mut best =
                direct_candidate(co_mvs, MotionVectorDelta { dx: 0, dy: 0 }, trb, trd, mode);
            let mut best_cost = candidate_sad(&best, &anchors, &src, mb_x, mb_y, mode);
            for dy in -DIRECT_SEARCH..=DIRECT_SEARCH {
                for dx in -DIRECT_SEARCH..=DIRECT_SEARCH {
                    if (dx, dy) == (0, 0) {
                        continue;
                    }
                    let cand =
                        direct_candidate(co_mvs, MotionVectorDelta { dx, dy }, trb, trd, mode);
                    let cost = candidate_sad(&cand, &anchors, &src, mb_x, mb_y, mode);
                    if cost < best_cost {
                        best_cost = cost;
                        best = cand;
                    }
                }
            }

            // Forward / backward motion search against each anchor.
            let (mv_f, _) = estimate_motion(&src, &fwd_luma, mb_x, mb_y, mode, fcode);
            let (mv_b, _) = estimate_motion(&src, &bwd_luma, mb_x, mb_y, mode, fcode);
            let zero = MotionVector { x: 0, y: 0 };
            for cand in [
                one_mv_candidate(BVopMbType::Forward, mv_f, zero, mode),
                one_mv_candidate(BVopMbType::Backward, zero, mv_b, mode),
                one_mv_candidate(BVopMbType::Interpolated, mv_f, mv_b, mode),
            ] {
                let bias = if cand.decode.mb_type == BVopMbType::Interpolated {
                    INTERP_MODE_BIAS
                } else {
                    ONE_MV_MODE_BIAS
                };
                let cost =
                    candidate_sad(&cand, &anchors, &src, mb_x, mb_y, mode).saturating_add(bias);
                if cost < best_cost {
                    best_cost = cost;
                    best = cand;
                }
            }

            // ---- Quantiser -------------------------------------------
            // dbquant rides only non-direct macroblocks with cbpb != 0;
            // plan the step now, commit it below once the syntax is
            // known to carry it.
            let (qp, dbquant) = if cfg.adaptive_quant && best.decode.mb_type != BVopMbType::Direct {
                let class =
                    crate::mb_quant::activity_class(crate::pvop_encode::intra_activity(&src));
                crate::mb_quant::plan_dbquant(running_qp, crate::mb_quant::target_qp(vop_qp, class))
            } else {
                (running_qp, None)
            };

            // ---- Residual --------------------------------------------
            let pred =
                best.decode
                    .reconstruct(&anchors, &InterMacroblock::zero(), mb_x, mb_y, 0, mode, 8);
            let mut events: Vec<Vec<AcEvent>> = Vec::with_capacity(6);
            for i in 0..6 {
                let src_block = frame.block(mb_row, mb_col, i);
                let mut residual = [[0i32; 8]; 8];
                for y in 0..8 {
                    for x in 0..8 {
                        let p = match i {
                            0..=3 => pred.luma[y + 8 * (i / 2)][x + 8 * (i % 2)],
                            4 => pred.cb[y][x],
                            _ => pred.cr[y][x],
                        };
                        residual[y][x] = src_block[y][x] - p;
                    }
                }
                let (ev, _qf) = quantise_inter_block(
                    &residual,
                    qp,
                    cfg.quant_type,
                    &w_inter,
                    crate::scan::ScanType::Zigzag,
                );
                events.push(ev);
            }
            let all_zero = events.iter().all(|e| e.is_empty());
            // cbpb: bit 5 = block 0 (Y TL) … bit 0 = block 5 (Cr).
            let cbpb: u8 = events
                .iter()
                .enumerate()
                .map(|(i, e)| u8::from(!e.is_empty()) << (5 - i))
                .sum();

            let mb_type = best.decode.mb_type;

            // ---- Emission --------------------------------------------
            if mb_type == BVopMbType::Direct
                && best.direct_delta == (MotionVectorDelta { dx: 0, dy: 0 })
                && all_zero
            {
                // modb "1": direct, zero delta, nothing coded.
                pw.writer().write_bit(true);
                stats.modb_one += 1;
                continue;
            }
            if all_zero {
                // modb "01": mb_type present, no cbpb.
                pw.writer().write_bit(false);
                pw.writer().write_bit(true);
            } else {
                // modb "00": mb_type + cbpb.
                pw.writer().write_bit(false);
                pw.writer().write_bit(false);
            }
            put_b_mb_type(pw.writer(), mb_type);
            if !all_zero {
                pw.writer().write_bits(u32::from(cbpb), 6);
            }
            // dbquant — present iff non-direct && cbpb != 0 (§6.2.6):
            // the planned Table 6-33 step (or "0" → delta 0), and the
            // only place the running quantiser moves.
            if mb_type != BVopMbType::Direct && !all_zero && cbpb != 0 {
                crate::vlc_encode::put_dbquant(pw.writer(), dbquant.unwrap_or(0));
                running_qp = qp;
                if dbquant.is_some() {
                    stats.dbquant += 1;
                }
            }

            // Motion bodies in §6.2.6 order: forward, backward, direct.
            match mb_type {
                BVopMbType::Forward => {
                    let mv = best.decode.mvs[0].forward;
                    put_motion_vector(pw.writer(), mv.x - pred_f.x, mv.y - pred_f.y, fcode);
                    pred_f = mv;
                    stats.forward += 1;
                }
                BVopMbType::Backward => {
                    let mv = best.decode.mvs[0].backward;
                    put_motion_vector(pw.writer(), mv.x - pred_b.x, mv.y - pred_b.y, fcode);
                    pred_b = mv;
                    stats.backward += 1;
                }
                BVopMbType::Interpolated => {
                    let f = best.decode.mvs[0].forward;
                    let b = best.decode.mvs[0].backward;
                    put_motion_vector(pw.writer(), f.x - pred_f.x, f.y - pred_f.y, fcode);
                    put_motion_vector(pw.writer(), b.x - pred_b.x, b.y - pred_b.y, fcode);
                    pred_f = f;
                    pred_b = b;
                    stats.interpolated += 1;
                }
                BVopMbType::Direct => {
                    // §7.6.8: predictor zero, f_code 1; bank untouched.
                    put_motion_vector(pw.writer(), best.direct_delta.dx, best.direct_delta.dy, 1);
                    stats.direct += 1;
                }
            }

            // Texture: Table B.17 inter EVENTs per coded block.
            for ev in &events {
                if !ev.is_empty() {
                    put_ac_events(pw.writer(), TcoefTable::Inter, ev);
                }
            }
        }
    }
    stats.packets = pw.packets_cut();
    let bytes = pw.finish();
    let recon = reconstruct_own_b_vop(vol, &bytes, store, anchor_motion, trb, trd);
    (bytes, recon, stats)
}

/// Decode an emitted B-VOP unit through the crate's own decoder walk
/// against the anchors in `store` (a B-VOP never enters the chain) —
/// the closed-loop reconstruction.
pub fn reconstruct_own_b_vop(
    vol: &crate::vol::VolHeader,
    unit: &[u8],
    store: &FrameStore,
    anchor_motion: Option<&[PvopMbMotion]>,
    trb: i32,
    trd: i32,
) -> DecodedFrame {
    let (mb_width, mb_height) = (
        usize::from(vol.width).div_ceil(16),
        usize::from(vol.height).div_ceil(16),
    );
    let mut br = BitReader::new(unit);
    let sc = br.read_bits(32).expect("unit starts with a start code");
    assert_eq!(sc, VOP_START_CODE, "encoder emitted a malformed unit");
    let vop = parse_vop_header_body(
        &mut br,
        vol.time_increment_resolution,
        VopContext::from_vol(vol),
    )
    .expect("own VOP header must parse");
    assert!(matches!(vop.coding_type, VopCodingType::B));
    let entries = decode_b_vop_macroblocks(
        &mut br,
        vol,
        &vop,
        trb,
        trd,
        anchor_motion,
        crate::compat::DecodeOptions::spec(),
    )
    .expect("own B-VOP payload must decode");
    crate::frame_decode::assemble_b_vop_frame(
        store,
        mb_width,
        mb_height,
        &entries,
        vop.rounding_type,
        sample_mode_of(vol),
        8,
    )
    .expect("own B-VOP must assemble")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn b_vop_header_round_trips() {
        let mut bw = BitWriter::new();
        write_b_vop_header(&mut bw, 25, 2, 7, 9, 1, None, 0);
        bw.next_start_code();
        let bytes = bw.into_bytes();
        let mut br = BitReader::new(&bytes);
        assert_eq!(br.read_bits(32).unwrap(), VOP_START_CODE);
        let vop = parse_vop_header_body(&mut br, 25, VopContext::default()).unwrap();
        assert!(matches!(vop.coding_type, VopCodingType::B));
        assert_eq!(vop.modulo_time_base, 2);
        assert_eq!(vop.time_increment, 7);
        assert_eq!(vop.quant, 9);
        assert_eq!(vop.fcode_fwd, 1);
        assert_eq!(vop.fcode_bwd, 1);
    }

    #[test]
    fn mb_type_codes_match_table_b4() {
        // Emit each type and decode through the crate's own Table B.4
        // parser path (modb "01" + mb_type).
        use crate::bvop::{parse_b_vop_mb_header, BMbTypeTable};
        use crate::vol::parse_video_object_layer;
        let cfg = EncoderConfig {
            width: 16,
            height: 16,
            ..EncoderConfig::default()
        };
        let headers = crate::ivop_encode::write_configuration_headers(&cfg);
        let pos = headers
            .windows(4)
            .position(|w| w == [0, 0, 1, 0x20])
            .unwrap();
        let vol = parse_video_object_layer(&headers[pos..], cfg.profile_and_level()).unwrap();
        for ty in [
            BVopMbType::Direct,
            BVopMbType::Interpolated,
            BVopMbType::Backward,
            BVopMbType::Forward,
        ] {
            let mut bw = BitWriter::new();
            bw.write_bit(false);
            bw.write_bit(true); // modb "01"
            put_b_mb_type(&mut bw, ty);
            bw.next_start_code();
            let bytes = bw.into_bytes();
            let mut br = BitReader::new(&bytes);
            let header =
                parse_b_vop_mb_header(&mut br, &vol, VopCodingType::B, BMbTypeTable::B4).unwrap();
            assert_eq!(header.mb_type, ty);
            assert!(header.mb_type_present);
            assert!(header.cbpb.is_none());
        }
    }
}
