//! §6.1.3.7.1 (4:2:0) binary-shape decimation — derive the chrominance
//! shape mask from the luminance shape mask for the §7.6.1.4 chroma
//! padding pass.
//!
//! ## Spec framing
//!
//! §7.6.1.4 ("Padding for chrominance components") says verbatim:
//!
//! > Chrominance components are padded according to subclauses
//! > 7.6.1.1 through 7.6.1.3 for each 8 × 8 block. The padding is
//! > performed by referring to a shape block generated by **decimating
//! > the shape block of the corresponding luminance component**. This
//! > decimating of the shape block is performed by the subsampling
//! > process described in subclause 6.1.3.6.
//!
//! The §7.6.1.4 reference to "§6.1.3.6" is the 3rd-edition pointer to
//! the §6.1.3.7.1 "4:2:0 Format" subclause that actually carries the
//! decimation rule. That subclause specifies:
//!
//! > For each 2 × 2 block of the binary alpha plane associated with
//! > the luminance plane of the bounding rectangle (of the same frame
//! > for the progressive and of the same field for the interlaced
//! > case), the associated pixel value of the binary alpha plane
//! > associated with the chrominance planes is set to 255 if any pixel
//! > of said 2 × 2 block of the binary alpha plane associated with the
//! > luminance plane equals 255.
//!
//! That is: the chroma shape sample at chroma position `(cy, cx)` is
//! opaque iff **any** of the four luma shape samples at luma positions
//! `(2*cy, 2*cx)`, `(2*cy, 2*cx + 1)`, `(2*cy + 1, 2*cx)`,
//! `(2*cy + 1, 2*cx + 1)` is opaque. A logical OR over each 2 × 2 luma
//! block.
//!
//! ## What this module exposes
//!
//! * [`decimate_chroma_shape_sample`] — single-sample 2 × 2 OR (the
//!   primitive the spec quotes verbatim).
//! * [`decimate_chroma_shape_progressive`] — frame-mode 16 × 16 luma
//!   shape → 8 × 8 chroma shape. The progressive case is the default
//!   path; §6.1.3.7.1 says "of the same frame for the progressive case".
//! * [`decimate_chroma_shape_interlaced_field`] — interlaced per-field
//!   16 × 16 luma shape → 8 × 8 chroma shape. The §6.1.3.7.1 interlaced
//!   path picks the 2 × 2 luma block "of the same field" — the function
//!   accepts a single field's 8-line luma shape and decimates it to a
//!   4-line chroma shape (one field of a 4:2:0 interlaced VOP). The
//!   per-field 4-line chroma output stacks back into the 8-line chroma
//!   block via [`stack_interlaced_chroma_shape`] for callers that need
//!   the merged frame view.
//! * [`stack_interlaced_chroma_shape`] — re-interleave the two
//!   per-field chroma shape blocks the §6.1.3.7.1 "of the same field"
//!   rule produces, back into a single 8-row frame block. The §7.6.1.5
//!   interlaced wrapper consumes the *per-field* output directly; the
//!   stacked form is for callers that route a single chroma block
//!   through the §7.6.1.4 entry points.
//!
//! ## What this module does **not** do
//!
//! * Cover the 4:2:2 or 4:4:4 chroma formats. §7.6.1.4 cross-references
//!   §6.1.3.6 / §6.1.3.7.1 — both define the decimation rule for the
//!   4:2:0 case only. The §6.1.3.7.2 (4:2:2) and §6.1.3.7.3 (4:4:4)
//!   subclauses describe sample positioning but do not specify a
//!   chroma-shape decimation rule (the decimation ratios change and
//!   the spec does not extend the §6.1.3.7.1 2 × 2 OR to them).
//! * Drive the §7.6.1 padding pipeline on the chroma block itself.
//!   That is the §7.6.1.4 caller-side composition step
//!   (`horizontal_repetitive_padding_chroma` → `vertical_repetitive_padding_chroma`
//!   → `extended_padding_chroma`) — see `sample_padding`,
//!   `vertical_padding`, and `extended_padding`. The role of this
//!   module is **only** to produce the chroma shape mask those three
//!   passes need.
//! * Decide between the progressive and interlaced paths. The caller
//!   inspects the VOP-level `interlaced` flag from §6.2.3 and picks
//!   [`decimate_chroma_shape_progressive`] or
//!   [`decimate_chroma_shape_interlaced_field`] accordingly.
//!
//! ## Const-generic parametrisation
//!
//! The primitive [`decimate_chroma_shape`] is `const`-generic in the
//! chroma side length `M`. The §7.6.1.4 8 × 8 chroma block is `M = 8`
//! and the §6.1.3.4 luma side is `2 * M = 16`; the [`CHROMA_SIDE`] and
//! [`LUMA_SIDE`] constants in [`crate::sample_padding`] are the two
//! convenience pin-points. The const-generic shape lets callers feed
//! a smaller block (e.g. for the §7.6.1.5 per-field 8 × 4 path the
//! interlaced primitive accepts an `8 × 16` luma block and emits a
//! `4 × 8` chroma block) without paying for a heap allocation.

#![allow(clippy::needless_range_loop)]

use crate::sample_padding::{SamplePresence, CHROMA_SIDE, LUMA_SIDE};

/// §6.1.3.7.1 decimation of a single 2 × 2 luminance shape block to one
/// chroma shape sample.
///
/// Returns [`SamplePresence::Opaque`] iff **any** of the four input
/// samples is opaque. This is the logical OR the spec text quotes
/// verbatim.
#[inline]
pub fn decimate_chroma_shape_sample(block: [SamplePresence; 4]) -> SamplePresence {
    if block.iter().any(|s| s.is_opaque()) {
        SamplePresence::Opaque
    } else {
        SamplePresence::Transparent
    }
}

/// §6.1.3.7.1 decimation primitive — `(2M) × (2M)` luma shape into
/// `M × M` chroma shape via per-2 × 2 OR.
///
/// `luma[y][x]` is the luminance shape mask; `chroma[cy][cx]` is the
/// returned chrominance shape mask. The function is the const-generic
/// kernel both [`decimate_chroma_shape_progressive`] (with `M = 8`,
/// luma side 16) and the §7.6.1.5 per-field interlaced path (with
/// `M = 8`, luma side 16, but operating on a single field's 8 lines
/// reshaped as 4 chroma lines — see
/// [`decimate_chroma_shape_interlaced_field`]) reuse.
pub fn decimate_chroma_shape<const M: usize, const TWO_M: usize>(
    luma: &[[SamplePresence; TWO_M]; TWO_M],
) -> [[SamplePresence; M]; M] {
    // `const_assert` via debug_assert at runtime: TWO_M must equal 2*M.
    // The §6.1.3.7.1 rule is fixed at the 2 × 2 decimation ratio; the
    // type-level guard prevents accidental misuse (e.g. wiring 4:2:2 or
    // 4:4:4 through this primitive).
    debug_assert_eq!(
        TWO_M,
        2 * M,
        "decimate_chroma_shape: TWO_M ({TWO_M}) must equal 2*M ({M})"
    );
    let mut chroma = [[SamplePresence::Transparent; M]; M];
    for cy in 0..M {
        for cx in 0..M {
            let ly = 2 * cy;
            let lx = 2 * cx;
            chroma[cy][cx] = decimate_chroma_shape_sample([
                luma[ly][lx],
                luma[ly][lx + 1],
                luma[ly + 1][lx],
                luma[ly + 1][lx + 1],
            ]);
        }
    }
    chroma
}

/// §6.1.3.7.1 progressive-frame chroma-shape decimation —
/// 16 × 16 luma shape → 8 × 8 chroma shape.
///
/// Drives [`decimate_chroma_shape`] at `M = 8`, `TWO_M = 16` for the
/// progressive (`interlaced == 0`) 4:2:0 case. The output is the
/// `8 × 8` shape block the §7.6.1.4 padding pipeline routes into
/// [`crate::sample_padding::horizontal_repetitive_padding_chroma`] /
/// [`crate::vertical_padding::vertical_repetitive_padding_chroma`] /
/// [`crate::extended_padding::extended_padding_chroma`].
pub fn decimate_chroma_shape_progressive(
    luma: &[[SamplePresence; LUMA_SIDE]; LUMA_SIDE],
) -> [[SamplePresence; CHROMA_SIDE]; CHROMA_SIDE] {
    decimate_chroma_shape::<CHROMA_SIDE, LUMA_SIDE>(luma)
}

/// §6.1.3.7.1 + §7.6.1.5 interlaced per-field chroma-shape decimation —
/// one 8 × 16 luma field → one 4 × 8 chroma field.
///
/// The §6.1.3.7.1 interlaced rule says the 2 × 2 OR is taken "of the
/// same field". Each field of a 4:2:0 interlaced macroblock contains 8
/// luma lines (the 16-line frame block split into two 8-line fields by
/// row parity); the corresponding chroma field has 4 lines (the
/// 8-line frame chroma block split into two 4-line fields). The
/// per-field 2 × 2 OR over the 8-line luma field's `(2*cy, 2*cx)..=
/// (2*cy + 1, 2*cx + 1)` window yields the 4 × 8 chroma field.
///
/// The §7.6.1.5 wrapper calls this once per field and then either
/// routes the per-field chroma shape into the §7.6.1.4 per-field
/// padding directly, or re-interleaves the two outputs via
/// [`stack_interlaced_chroma_shape`] for a merged frame view.
pub fn decimate_chroma_shape_interlaced_field(
    luma_field: &[[SamplePresence; LUMA_SIDE]; CHROMA_SIDE],
) -> [[SamplePresence; CHROMA_SIDE]; CHROMA_FIELD_LINES] {
    let mut chroma_field = [[SamplePresence::Transparent; CHROMA_SIDE]; CHROMA_FIELD_LINES];
    for cy in 0..CHROMA_FIELD_LINES {
        for cx in 0..CHROMA_SIDE {
            let ly = 2 * cy;
            let lx = 2 * cx;
            chroma_field[cy][cx] = decimate_chroma_shape_sample([
                luma_field[ly][lx],
                luma_field[ly][lx + 1],
                luma_field[ly + 1][lx],
                luma_field[ly + 1][lx + 1],
            ]);
        }
    }
    chroma_field
}

/// Number of chroma lines per field in a 4:2:0 interlaced macroblock.
///
/// Equal to [`CHROMA_SIDE`] / 2. Each field contributes half of the
/// 8-line chroma block; the §7.6.1.5 wrapper either processes them
/// individually or stacks them back via
/// [`stack_interlaced_chroma_shape`].
pub const CHROMA_FIELD_LINES: usize = CHROMA_SIDE / 2;

/// Re-interleave two per-field chroma shape blocks back into a single
/// 8 × 8 frame chroma shape.
///
/// `top` is the top-field chroma shape (lines at even chroma rows in
/// the frame view); `bottom` is the bottom-field chroma shape (lines
/// at odd chroma rows). The output places `top[0]` at row 0, `bottom[0]`
/// at row 1, `top[1]` at row 2, …, `bottom[3]` at row 7 — matching the
/// frame-level row interleaving that §6.1.3.7.1 inverts when it picks
/// the per-field 2 × 2 luma block.
pub fn stack_interlaced_chroma_shape(
    top: &[[SamplePresence; CHROMA_SIDE]; CHROMA_FIELD_LINES],
    bottom: &[[SamplePresence; CHROMA_SIDE]; CHROMA_FIELD_LINES],
) -> [[SamplePresence; CHROMA_SIDE]; CHROMA_SIDE] {
    let mut frame = [[SamplePresence::Transparent; CHROMA_SIDE]; CHROMA_SIDE];
    for f in 0..CHROMA_FIELD_LINES {
        frame[2 * f] = top[f];
        frame[2 * f + 1] = bottom[f];
    }
    frame
}

/// Split a 16 × 16 frame luma shape into two per-field 8 × 16 luma
/// shape blocks (top + bottom field by row parity).
///
/// Convenience helper for callers driving the §7.6.1.5 interlaced
/// per-field path: pull the per-field luma fields out of the frame
/// shape block in one place, then route each through
/// [`decimate_chroma_shape_interlaced_field`].
pub fn split_luma_shape_into_fields(
    luma_frame: &[[SamplePresence; LUMA_SIDE]; LUMA_SIDE],
) -> (
    [[SamplePresence; LUMA_SIDE]; CHROMA_SIDE],
    [[SamplePresence; LUMA_SIDE]; CHROMA_SIDE],
) {
    let mut top = [[SamplePresence::Transparent; LUMA_SIDE]; CHROMA_SIDE];
    let mut bottom = [[SamplePresence::Transparent; LUMA_SIDE]; CHROMA_SIDE];
    for f in 0..CHROMA_SIDE {
        top[f] = luma_frame[2 * f];
        bottom[f] = luma_frame[2 * f + 1];
    }
    (top, bottom)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn op() -> SamplePresence {
        SamplePresence::Opaque
    }

    fn tr() -> SamplePresence {
        SamplePresence::Transparent
    }

    // --- Single-sample primitive --------------------------------------

    #[test]
    fn sample_all_transparent_is_transparent() {
        assert_eq!(decimate_chroma_shape_sample([tr(), tr(), tr(), tr()]), tr());
    }

    #[test]
    fn sample_all_opaque_is_opaque() {
        assert_eq!(decimate_chroma_shape_sample([op(), op(), op(), op()]), op());
    }

    #[test]
    fn sample_any_one_opaque_is_opaque() {
        // The spec rule is verbatim "if any pixel of said 2×2 block …
        // equals 255". Each of the four positions must individually
        // promote the output to opaque.
        for pos in 0..4 {
            let mut block = [tr(), tr(), tr(), tr()];
            block[pos] = op();
            assert_eq!(
                decimate_chroma_shape_sample(block),
                op(),
                "position {pos} opaque should promote output to opaque"
            );
        }
    }

    #[test]
    fn sample_three_opaque_one_transparent_is_opaque() {
        for tr_pos in 0..4 {
            let mut block = [op(), op(), op(), op()];
            block[tr_pos] = tr();
            assert_eq!(
                decimate_chroma_shape_sample(block),
                op(),
                "single transparent at {tr_pos} should not block opaque"
            );
        }
    }

    // --- Progressive 16×16 → 8×8 ---------------------------------------

    #[test]
    fn progressive_all_transparent_yields_all_transparent() {
        let luma = [[tr(); LUMA_SIDE]; LUMA_SIDE];
        let chroma = decimate_chroma_shape_progressive(&luma);
        for row in chroma.iter() {
            for &s in row.iter() {
                assert_eq!(s, tr());
            }
        }
    }

    #[test]
    fn progressive_all_opaque_yields_all_opaque() {
        let luma = [[op(); LUMA_SIDE]; LUMA_SIDE];
        let chroma = decimate_chroma_shape_progressive(&luma);
        for row in chroma.iter() {
            for &s in row.iter() {
                assert_eq!(s, op());
            }
        }
    }

    #[test]
    fn progressive_single_luma_opaque_promotes_its_chroma_cell() {
        // Set exactly one luma position opaque; verify the matching
        // chroma cell is opaque and every other cell is transparent.
        for ly in 0..LUMA_SIDE {
            for lx in 0..LUMA_SIDE {
                let mut luma = [[tr(); LUMA_SIDE]; LUMA_SIDE];
                luma[ly][lx] = op();
                let chroma = decimate_chroma_shape_progressive(&luma);
                let target_cy = ly / 2;
                let target_cx = lx / 2;
                for cy in 0..CHROMA_SIDE {
                    for cx in 0..CHROMA_SIDE {
                        let expected = if cy == target_cy && cx == target_cx {
                            op()
                        } else {
                            tr()
                        };
                        assert_eq!(
                            chroma[cy][cx], expected,
                            "luma({ly},{lx}) opaque → chroma({cy},{cx}) expected {expected:?}"
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn progressive_half_opaque_left_half_yields_half_opaque_chroma() {
        // Luma rows 0..16, columns 0..8 opaque; columns 8..16
        // transparent. Each chroma column 0..4 covers two opaque luma
        // columns → opaque. Each chroma column 4..8 covers two
        // transparent luma columns → transparent.
        let mut luma = [[tr(); LUMA_SIDE]; LUMA_SIDE];
        for ly in 0..LUMA_SIDE {
            for lx in 0..LUMA_SIDE / 2 {
                luma[ly][lx] = op();
            }
        }
        let chroma = decimate_chroma_shape_progressive(&luma);
        for cy in 0..CHROMA_SIDE {
            for cx in 0..CHROMA_SIDE {
                let expected = if cx < CHROMA_SIDE / 2 { op() } else { tr() };
                assert_eq!(chroma[cy][cx], expected);
            }
        }
    }

    #[test]
    fn progressive_single_opaque_in_2x2_block_promotes_only_that_chroma_cell() {
        // Each 2×2 luma block independently sets one chroma cell. Put
        // one opaque luma in every 2×2 block; expect the entire chroma
        // block opaque.
        let mut luma = [[tr(); LUMA_SIDE]; LUMA_SIDE];
        for cy in 0..CHROMA_SIDE {
            for cx in 0..CHROMA_SIDE {
                luma[2 * cy][2 * cx] = op();
            }
        }
        let chroma = decimate_chroma_shape_progressive(&luma);
        for cy in 0..CHROMA_SIDE {
            for cx in 0..CHROMA_SIDE {
                assert_eq!(chroma[cy][cx], op());
            }
        }
    }

    #[test]
    fn progressive_corner_only_luma_block_yields_one_corner_chroma() {
        // The 2×2 block at luma (14,14)..(15,15) maps to chroma (7,7).
        // Mark only that block opaque; verify only chroma (7,7) is opaque.
        let mut luma = [[tr(); LUMA_SIDE]; LUMA_SIDE];
        luma[14][14] = op();
        luma[14][15] = op();
        luma[15][14] = op();
        luma[15][15] = op();
        let chroma = decimate_chroma_shape_progressive(&luma);
        for cy in 0..CHROMA_SIDE {
            for cx in 0..CHROMA_SIDE {
                let expected = if cy == 7 && cx == 7 { op() } else { tr() };
                assert_eq!(chroma[cy][cx], expected);
            }
        }
    }

    #[test]
    fn progressive_diagonal_luma_band_yields_diagonal_chroma() {
        // Luma diagonal (y == x) opaque. Each 2×2 block at chroma (c, c)
        // contains luma (2c,2c) and (2c+1,2c+1) on the diagonal — both
        // opaque. Each off-diagonal 2×2 block contains no diagonal luma.
        let mut luma = [[tr(); LUMA_SIDE]; LUMA_SIDE];
        for y in 0..LUMA_SIDE {
            luma[y][y] = op();
        }
        let chroma = decimate_chroma_shape_progressive(&luma);
        for cy in 0..CHROMA_SIDE {
            for cx in 0..CHROMA_SIDE {
                let expected = if cy == cx { op() } else { tr() };
                assert_eq!(chroma[cy][cx], expected);
            }
        }
    }

    // --- Interlaced per-field 8×16 → 4×8 -------------------------------

    #[test]
    fn interlaced_per_field_all_transparent_yields_all_transparent() {
        let field = [[tr(); LUMA_SIDE]; CHROMA_SIDE];
        let chroma_field = decimate_chroma_shape_interlaced_field(&field);
        for row in chroma_field.iter() {
            for &s in row.iter() {
                assert_eq!(s, tr());
            }
        }
    }

    #[test]
    fn interlaced_per_field_all_opaque_yields_all_opaque() {
        let field = [[op(); LUMA_SIDE]; CHROMA_SIDE];
        let chroma_field = decimate_chroma_shape_interlaced_field(&field);
        for row in chroma_field.iter() {
            for &s in row.iter() {
                assert_eq!(s, op());
            }
        }
    }

    #[test]
    fn interlaced_per_field_single_opaque_promotes_one_chroma_cell() {
        // Each field has 8 luma lines × 16 columns → 4 chroma lines × 8 columns.
        for ly in 0..CHROMA_SIDE {
            for lx in 0..LUMA_SIDE {
                let mut field = [[tr(); LUMA_SIDE]; CHROMA_SIDE];
                field[ly][lx] = op();
                let chroma_field = decimate_chroma_shape_interlaced_field(&field);
                let target_cy = ly / 2;
                let target_cx = lx / 2;
                for cy in 0..CHROMA_FIELD_LINES {
                    for cx in 0..CHROMA_SIDE {
                        let expected = if cy == target_cy && cx == target_cx {
                            op()
                        } else {
                            tr()
                        };
                        assert_eq!(chroma_field[cy][cx], expected);
                    }
                }
            }
        }
    }

    // --- split / stack round-trip -------------------------------------

    #[test]
    fn split_then_stack_round_trips_arbitrary_chroma_pattern() {
        // Build an arbitrary luma frame shape, run the interlaced
        // per-field decimation on each field, stack the per-field
        // chroma outputs, and verify the result matches the
        // progressive frame-mode decimation. This is the round-trip
        // property: a frame-mode decimation equals
        // stack(decimate(top), decimate(bottom)) **only when the
        // top/bottom 2×2 luma blocks the §6.1.3.7.1 progressive case
        // would pick are the same as the per-field 2×2 luma blocks
        // the §6.1.3.7.1 interlaced case picks** — which holds when
        // the luma block has uniform field rows (no inter-field
        // sample swap). We construct a uniform luma frame here to
        // exercise both code paths against the same expected output.
        let mut luma = [[tr(); LUMA_SIDE]; LUMA_SIDE];
        for ly in 0..LUMA_SIDE {
            for lx in 0..LUMA_SIDE {
                luma[ly][lx] = if (ly / 4 + lx / 4) % 2 == 0 {
                    op()
                } else {
                    tr()
                };
            }
        }
        let progressive = decimate_chroma_shape_progressive(&luma);

        let (top, bottom) = split_luma_shape_into_fields(&luma);
        let top_chroma = decimate_chroma_shape_interlaced_field(&top);
        let bottom_chroma = decimate_chroma_shape_interlaced_field(&bottom);
        let stacked = stack_interlaced_chroma_shape(&top_chroma, &bottom_chroma);

        // The 2 × 2 luma block at (2cy, 2cx) progressive coincides with
        // the field-block at (cy, 2cx) on the top field for cy even and
        // the (cy/2, 2cx) field-block on the bottom field for cy odd —
        // these two paths agree exactly when each field's per-2×2 OR
        // covers the same four luma samples the progressive path
        // covers, which is the case here.
        for cy in 0..CHROMA_SIDE {
            for cx in 0..CHROMA_SIDE {
                assert_eq!(
                    stacked[cy][cx], progressive[cy][cx],
                    "field-stack({cy},{cx}) must equal progressive({cy},{cx})"
                );
            }
        }
    }

    #[test]
    fn split_luma_extracts_correct_field_rows() {
        let mut luma = [[tr(); LUMA_SIDE]; LUMA_SIDE];
        // Mark each row uniquely so split-correctness is observable.
        for ly in 0..LUMA_SIDE {
            // Opaque cells indicate the row index parity.
            if ly % 2 == 0 {
                luma[ly][0] = op();
            } else {
                luma[ly][LUMA_SIDE - 1] = op();
            }
        }
        let (top, bottom) = split_luma_shape_into_fields(&luma);
        for f in 0..CHROMA_SIDE {
            assert_eq!(top[f][0], op(), "top field row {f} (luma row {})", 2 * f);
            assert_eq!(top[f][LUMA_SIDE - 1], tr());
            assert_eq!(
                bottom[f][0],
                tr(),
                "bottom field row {f} (luma row {})",
                2 * f + 1
            );
            assert_eq!(bottom[f][LUMA_SIDE - 1], op());
        }
    }

    #[test]
    fn stack_interlaced_chroma_interleaves_rows() {
        // Construct top and bottom field chroma blocks with all-opaque
        // and all-transparent fill respectively; check the merged
        // pattern alternates rows.
        let top = [[op(); CHROMA_SIDE]; CHROMA_FIELD_LINES];
        let bottom = [[tr(); CHROMA_SIDE]; CHROMA_FIELD_LINES];
        let frame = stack_interlaced_chroma_shape(&top, &bottom);
        for cy in 0..CHROMA_SIDE {
            for cx in 0..CHROMA_SIDE {
                let expected = if cy % 2 == 0 { op() } else { tr() };
                assert_eq!(frame[cy][cx], expected);
            }
        }
    }

    // --- Spec rule cross-check: §6.1.3.7.1 verbatim ----------------------

    #[test]
    fn spec_rule_any_pixel_equals_255_promotes_chroma() {
        // §6.1.3.7.1: "the associated pixel value of the binary alpha
        // plane associated with the chrominance planes is set to 255
        // if any pixel of said 2×2 block of the binary alpha plane
        // associated with the luminance plane equals 255". Exhaustively
        // try every 2^4 = 16 mask over a single 2 × 2 luma block and
        // verify the chroma cell is opaque iff the mask is non-zero.
        for mask in 0u8..16 {
            let block = [
                if mask & 1 != 0 { op() } else { tr() },
                if mask & 2 != 0 { op() } else { tr() },
                if mask & 4 != 0 { op() } else { tr() },
                if mask & 8 != 0 { op() } else { tr() },
            ];
            let expected = if mask != 0 { op() } else { tr() };
            assert_eq!(
                decimate_chroma_shape_sample(block),
                expected,
                "mask {mask:#b}: expected {expected:?}"
            );
        }
    }

    #[test]
    fn const_generic_kernel_matches_progressive_entry_point() {
        // Sanity: the §6.1.3.7.1 const-generic kernel
        // decimate_chroma_shape::<8,16> must agree with
        // decimate_chroma_shape_progressive across an arbitrary pattern.
        let mut luma = [[tr(); LUMA_SIDE]; LUMA_SIDE];
        for ly in 0..LUMA_SIDE {
            for lx in 0..LUMA_SIDE {
                luma[ly][lx] = if (ly * 31 + lx * 17) % 7 < 3 {
                    op()
                } else {
                    tr()
                };
            }
        }
        let via_entry = decimate_chroma_shape_progressive(&luma);
        let via_kernel = decimate_chroma_shape::<CHROMA_SIDE, LUMA_SIDE>(&luma);
        assert_eq!(via_entry, via_kernel);
    }
}
